Name: Xiaofeng Ma \
Aalto Student Number: 100315653

In [22]:
import numpy as np
import pandas as pd

In [23]:
%%timeit
print(np.random.rand(100_000_000).sum())

49995031.3677746
50001595.67481073
50003677.61636665
50004773.10581965
49997036.617159486
49996500.87009456
49999391.09056739
49996083.0618755
985 ms ± 110 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [24]:
%%timeit
print(np.random.rand(200_000_000).sum())
# almost twice as long as the last one.

100003000.2283702
99999781.00098132
99997600.88588957
99996431.92105505
99996602.17509855
99994368.08404912
99996861.38970684
99999338.34274848
1.85 s ± 78.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [25]:
def ravel(row,col,n_rows,n_cols):
    idx = n_cols*row+col
    return idx

In [26]:
print(ravel(2, 3, n_rows=4, n_cols=4))
print(ravel(2, 3, n_rows=4, n_cols=8))
print(ravel(0, 0, n_rows=1, n_cols=1))
print(ravel(3, 3, n_rows=4, n_cols=4))
print(ravel(3_465, 18_923, n_rows=10_000, n_cols=20_000))

11
19
0
15
69318923


In [27]:
print(ravel(0, 4, 3, 12))
print(ravel(1, 0, 3, 12))
print(ravel(1, 4, 3, 12))

4
12
16


In [28]:
np.zeros((3, 5)).strides

(40, 8)

In [29]:
a = np.random.rand(20, 10)
print(a.strides)
print(a.reshape(2,-1).strides)

(80, 8)
(800, 8)


In [30]:
a = np.zeros((5, 5))
print(a.base)  # None
print(a)
b = a[:2, :2]
print(b.base.shape)  # (5, 5)
print(b.base)
print(b)

None
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(5, 5)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]]


In [31]:
b[0, 0] = 1.
print(a)  # Original matrix was modified
print(b)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0.]
 [0. 0.]]


In [32]:
# what happens to b if we change a:
a[0, 1] = 1.
print(a)
print(b)
# The element at [0,1] of b also changed.

[[1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1.]
 [0. 0.]]


In [33]:
c = a[[0, 2]]  # Select rows 0 and 2
print(c.base)  # None. So not a view.

None


In [34]:
d = a[0, 2]
print(d.base)

None


In [35]:
import copy
e = copy.copy(a[:2, :2])

# copy
print(e)
print(e.base)

# view
print(b)
print(b.base)
print(b.base.shape)  # (5, 5)


[[1. 1.]
 [0. 0.]]
None
[[1. 1.]
 [0. 0.]]
[[1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(5, 5)


In [36]:
f = a + 1
print(f)
print(f.base)

[[2. 2. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
None


I finally understood the reason why we can't directly assign arrays with "=" in python sometimes. I've encountered strange phenomena before because of this. Matlab doesn't have such problems, so I thought python was so strange at the time.

In [37]:
runners = pd.DataFrame([
              {'Runner': 'Runner 1', 400: 64, 800: 128, 1200: 192, 1500: 240},
              {'Runner': 'Runner 2', 400: 80, 800: 160, 1200: 240, 1500: 300},
              {'Runner': 'Runner 3', 400: 96, 800: 192, 1200: 288, 1500: 360},
          ])

In [38]:
runners

Runner  400  800  1200  1500
0  Runner 1   64  128   192   240
1  Runner 2   80  160   240   300
2  Runner 3   96  192   288   360

In [39]:
runners[runners[400] > runners[400].mean()]

Runner  400  800  1200  1500
2  Runner 3   96  192   288   360

In [40]:
runners[runners[400] > runners[400].mean()][800].mean()

192.0

In [41]:
runners1 = pd.melt(runners, id_vars="Runner",
              value_vars=[400, 800, 1200, 1500],
              var_name="distance",
              value_name="time"
          )

In [42]:
runners1

Runner distance  time
0   Runner 1      400    64
1   Runner 2      400    80
2   Runner 3      400    96
3   Runner 1      800   128
4   Runner 2      800   160
5   Runner 3      800   192
6   Runner 1     1200   192
7   Runner 2     1200   240
8   Runner 3     1200   288
9   Runner 1     1500   240
10  Runner 2     1500   300
11  Runner 3     1500   360